### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by cmonacaps** [fluture-js/fluture-node#8]
tcp socket readable and writeable future-stream-futures that correctly communicate backpressure

http/2 use cases including exceedingly large get and post sizes and the effect on the rate of multiplexed small-sized get and post requests

might be useful to divide the domain into streams, network and protocol; possible that some namespaces could be aligned with nodejs api module names

**Comment by Avaq** [comment]
Hi @cmonacaps 

From what I understand, you are requesting a feature to do with something related to backpressure handling streams suited for http/2, but I'm not sure exactly what you're proposing.

Could you perhaps elaborate, rephrase, or illustrate (with code) your request to aid in my understanding?

Thank you, and my apologies for the friction.

**Comment by Avaq** [comment]
Without clarity on what's being asked, and no response from the author, I'm afraid I'm going to close this issue. @cmonacaps feel free to reopen it if you have some new information for us.
